title: Dev'In Périgueux
email: contact@dev-in-perigueux.fr
description: >-
  Une communauté de développeuses et de développeurs qui se retrouvent régulièrement pour aborder ensemble leur passion du développement logiciel. Web, systèmes embarqués, données… un rendez-vous complètement irrégulier avec des gens qui sortent de l'ordinaire !
baseurl: ""
url: "https://dev-in-perigueux.fr"
twitter_username: devin_perigueux
github_username:  dev-in-perigueux
meetup_url: https://www.meetup.com/fr-FR/Dev-In-Perigueux/

permalink: /:year-:month-:title/

# Build settings
markdown: kramdown
theme: jekyll-athena

jekyll-athena:
  date_format: "%d/%m/%Y"
  translations:
    home: "Accueil"
    maintained_by: "Ce projet est maintenu par %s"
    page_previous: "Précédent"
    page_next: "Suivant"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: post
  -
    scope:
      path: "_members"
    values:
      layout: member

collections:
  members:
    output: true
    permalink: /membres/:slug

feed:
  path: feed.xml

exclude:
  - "Rakefile"
  - "LICENCE"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
